dist: trusty
sudo: false

import:
  - travis-ci/build-configs:db-setup.yml
  - source: travis-ci/build-configs:ship-docker.yml
    if: type != pull_request

rvm: 2.4.2

cache: bundler

env:
  global:
  - COVERAGE=1

services:
  - memcached
  - redis
  - rabbitmq

before_install:
  - bundle config https://gems.contribsys.com/ $BUNDLE_GEMS__CONTRIBSYS__COM

script: bundle exec rspec
