dist: trusty
sudo: false

import:
  - travis-ci/build-configs:db-setup.yml

rvm: 2.4.2

cache: bundler

env:
  global:
  - COVERAGE=1

services:
  - memcached
  - redis
  - rabbitmq

before_install:
  - bundle config https://gems.contribsys.com/ $BUNDLE_GEMS__CONTRIBSYS__COM

jobs:
  include:
    - stage: "testing time"
      script: bundle exec rspec
    - stage: ":ship: it to quay.io"
      ruby:
      services:
      addons:
      before_install: echo "skipping"
      install: echo "skipping"
      script: make ship
